# Generated by Django 5.0.6 on 2024-06-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CursosAlmacenados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('curso', models.CharField(max_length=10)),
                ('modulos', models.IntegerField()),
                ('precio', models.FloatField()),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Crear')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Editar')),
            ],
            options={
                'verbose_name': 'Cursos',
                'verbose_name_plural': 'Curso',
                'ordering': ['-created'],
            },
        ),
    ]
