# Generated by Django 5.0.6 on 2024-06-27 15:02

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('claveActividad', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Comentario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursosalmacenados', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Actividade',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-created'],
            },
        ),
    ]
